routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\AdminMiddleware;
use Illuminate\Support\Facades\Route;

Route::get( '/', function () {
	return view( 'welcome' );
} )->name( 'home' );


Route::get( '/admin',['middleware' => 'admin'], function () {
	return view( 'admin.dashboard.index' );

} );

Route::group( [ 'prefix' => 'admin', 'namespace' => 'admin','middleware' => 'admin'], function () {
	Route::get( '/urlshortner', 'UrlShortnerController@generate' )->name( 'admin.urlshortner' );
	Route::post( '/urlshortner', 'UrlShortnerController@store' )->name( 'admin.urlshortner' );
	Route::get( '/urlshortner/list', 'UrlShortnerController@show' )->name( 'admin.urlshortner.list' );
	Route::get( '/redirect/{code}', 'UrlShortnerController@redirect' );
} );


Route::group(['prefix' => 'admin','middleware' => 'admin'], function () {
	Route::resource('users', 'UsersController');
	Route::resource('agencies', 'AgencieController');
	Route::resource('posts', 'PostsController');
	Route::get('/agencies/{id}/tour', 'AgencieController@toure')->name('create.tour');
	Route::resource('tours', 'ToursController');
	Route::get('/','countController@index')->name('admin');
});



//Route::resource('agencies', 'AgencieController');


//Route::get( '/posts', 'PostController@index' );
//Route::get( '/posts/create', 'PostController@create' )->name( 'admin.posts.create' );
//Route::post( '/posts/create', 'PostController@store' );
//Route::get( '/posts/{post_id}', 'PostController@show' )->name( 'post.show' );



Route::get( '/realtime', 'realtimeController@test' );


Auth::routes();

Route::get( '/home', 'HomeController@index' );


Route::get( '/api', 'ApiController@index' );

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {

	use Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $guarded = [
		'id',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];

	public function roles() {
//		return $this->belongsToMany(Role::class,'user_roles','user_id','role_id');
		return $this->belongsToMany(Role::class);
	}

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Forms\ToursForm;
use App\Forms\UserForm;
use App\Http\Requests\UserRequest;
use App\Repositories\UserRepository;
use App\Role;
use App\User;
use App\role_user;
use Collective\Html\FormBuilder;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use Symfony\Component\Routing\Annotation\Route;

class UsersController extends Controller {
	/**
	 * @var UserRepository
	 */
	private $repository;

	/**
	 * UsersController constructor.
	 */
	public function __construct(UserRepository $repository) {
		$this->repository = $repository;
	}
	use FormBuilderTrait;


	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		$users = User::all();

		return view( 'admin.users.list',compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

//		$form = \FormBuilder::create(UserForm::class, [
//			'method' => 'POST',
//			'url'    => route( 'users.store' ),
//		]);

		$form = $this->form(UserForm::class, [
			'method' => 'POST',
			'url'    => route( 'users.store' ),
		]);


		return view( 'admin.users.create', compact( 'form' ) );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param UserRepository $user_repository
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(UserRequest $request) {

		$form = $this->form(UserForm::class);


		if (!$form->isValid()) {
			return redirect()->back()->withErrors($form->getErrors())->withInput();
		}
		$form->redirectIfNotValid();

		$user = $this->repository->create($request->only('name','email','password', 'role_ids'));

		return redirect()->route('users.edit',['id'=>$user->id]);

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {

		$user = User::findOrFail( $id );

		$model = $user->toArray();
		$model['role_ids'] = $user->roles->pluck( 'id' )->toArray();


		$form = \FormBuilder::create( UserForm::class, [
			'method' => 'PUT',
			'url'    => route( 'users.update', [ 'id' => $user->id ] ),
			'model'  => $model,
		] );

		return view( 'admin.users.edit', compact( 'form' ) );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( $id, Request $request) {

		$user = $this->repository->update( User::findOrFail( $id ), $request->only('name','email','password','role_ids'));

		return redirect()->route( 'users.edit', [ 'id' => $user->id ] );

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {

	}
}

app/Http/Controllers/fronend/UserController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;

class UserController extends Controller
{


}

resources/views/admin/users/create.blade.php
@extends('layout.admin')

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">

                    @include('admin.Partials.alert')

                    {!! form($form) !!}
                </div>
            </div>
        </div>
    </section>
    <!-- /.box -->

@endsection

resources/views/admin/users/edit.blade.php
@extends('layout.admin')

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">

                    {!! form($form) !!}


                </div>
            </div>
        </div>
    </section>
    <!-- /.box -->

@endsection

resources/views/admin/users/form.blade.php
@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">

                    <form role="form" method="post">

                        {{ csrf_field() }}

                        <div class="form-group">

                            @include('admin.Partials.alert')


                            <label for="full_name">نام کامل</label>
                            <input type="text" class="form-control" id="full_name" name="full_name">

                            <label for="email">ایمیل</label>
                            <input type="email" class="form-control" id="email" name="email">

                            <label for="password">رمز عبور</label>
                            <input type="password" class="form-control" id="password" name="password">

                            <label for="role">نقش کاربری</label>
                            <select name="role" id="role" class="form-control">
                                <option value="1">کاربر عادی</option>
                                <option value="2">اپراتور</option>
                                <option value="3">مدیریت</option>
                            </select>

                            <label for="wallet">موجودی کیف پول :</label>
                            <input type="text" value="0" class="form-control" id="wallet" name="wallet">

                                <button type="submit" class="btn btn-primary" name="submit_save_user">اضافه کردن کاربر</button>

                        </div>



                        {{--<div class="box-body">--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="exampleInputEmail1">ایمیل</label>--}}
                                {{--<input type="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل">--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="exampleInputPassword1">رمز عبور</label>--}}
                                {{--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="رمز عبور">--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="exampleInputFile">ارسال فایل</label>--}}
                                {{--<input type="file" id="exampleInputFile">--}}

                                {{--<p class="help-block">متن راهنما</p>--}}
                            {{--</div>--}}
                            {{--<div class="checkbox">--}}
                                {{--<label>--}}
                                    {{--<input type="checkbox"> مرا به خاطر بسپار--}}
                                {{--</label>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        <!-- /.box-body -->


                    </form>
                </div>
            </div>
        </div>
    </section>
                <!-- /.box -->

@endsection

resources/views/admin/users/list.blade.php
@include('admin.Partials.header')
@extends('layout.admin')
@include('admin.Partials.sidebar')

@section('title')
    لیست کاربران
@endsection

@include('admin.Partials.alert')
@section('content')

    @if($users && count($users) > 0)

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-9">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">لیست کاربران</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>شناسه</th>
                                    <th>نام کامل</th>
                                    <th>ایمیل</th>
                                    <th style="text-align: center">نقش کاربری</th>
                                    <th>عملیات</th>
                                </tr>
                                </thead>

                                @foreach($users as $user)

                                    <tr>
                                        <td> {{  $user->id }} </td>
                                        <td> {{  $user->name}} </td>
                                        <td>{{  $user->email }}</td>

                                        <td style="text-align: center">
                                            @foreach($user->roles as $rols)
                                                <p class="label label-success">
                                                {{ $rols->name }}
                                                </p>
                                            @endforeach
                                        </td>

                                        <td style="text-align: center">
                                            <a href="{{ route('users.edit',$user->id) }}">
                                                <li class="glyphicon glyphicon-edit"></li>
                                            </a>
                                            <a href="{{  route('users.destroy',$user->id)  }}">
                                                <li class="glyphicon glyphicon-trash"></li>
                                            </a>

                                        </td>


                                    </tr>

                                @endforeach


                                <tfoot>
                                <tr>
                                    <th>شناسه</th>
                                    <th>نام کامل</th>
                                    <th>ایمیل</th>
                                    <th style="text-align: center">نقش کاربری</th>
                                    <th>عملیات</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->


                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
        </div>

        </table>

    @else
        <h1>کاربری برای نمایش وجود ندارد</h1>
        <a href="/admin/users/create">
            <button class="form-control btn-success col-md-4">اضافه کردن کاربر جدید</button>
        </a>
    @endif




@endsection

@include('admin.Partials.footer')

resources/views/admin/users/opration.blade.php
<a href="{{ route('users.edit',$user->id) }}"> <li class="glyphicon glyphicon-edit"></li></a>
<a href="{{  route('users.destroy',$user->id)  }}"> <li class="glyphicon glyphicon-trash"></li></a>